namespace ObjektRT.Core.Model;

/// <summary>ObjectRT bytecode opcodes.
/// Table 0 (0x00-0x34) are single-byte in the bytecode stream.
/// Extension tables use 0xFF prefix bytes: 0xFF 0xNN = table 1,
/// 0xFF 0xFF 0xNN = table 2, etc. The flat value is table*256 + opcode.
/// </summary>
public enum Opcode : ushort
{
    Nop       = 0x00,
    Ldc       = 0x01,
    Ldstr     = 0x02,
    Ldarg     = 0x03,
    Starg     = 0x04,
    Ldloc     = 0x05,
    Stloc     = 0x06,
    Add       = 0x07,
    Sub       = 0x08,
    Mul       = 0x09,
    Div       = 0x0A,
    Rem       = 0x0B,
    Neg       = 0x0C,
    Ceq       = 0x0D,
    Cne       = 0x0E,
    Ldfld     = 0x0F,
    Ldsfld    = 0x10,
    Stsfld    = 0x11,
    Newobj    = 0x12,
    Newarr    = 0x13,
    Ldelem    = 0x14,
    Stelem    = 0x15,
    Call      = 0x16,
    Callvirt  = 0x17,
    Ret       = 0x18,
    If        = 0x19,
    While     = 0x1A,
    Break     = 0x1B,
    Continue  = 0x1C,
    Try       = 0x1D,
    Throw     = 0x1E,
    Conv      = 0x1F,
    Castclass = 0x20,
    Isinst    = 0x21,
    Dup       = 0x22,
    Pop       = 0x23,
    Ldnull    = 0x24,
    Not       = 0x25,
    Cgt       = 0x26,
    Cge       = 0x27,
    Clt       = 0x28,
    Cle       = 0x29,
    Stfld     = 0x2A,
    LdcI4     = 0x2B,
    LdcI8     = 0x2C,
    LdcR4     = 0x2D,
    LdcR8     = 0x2E,
    And       = 0x2F,
    Xor       = 0x30,
    Or        = 0x31,
    Br        = 0x32,
    Brtrue    = 0x33,
    Brfalse   = 0x34,
    NativeCall = 0x35,
    Ldlen     = 0x36,
    Shl       = 0x37,
    // ── Pointer operations (0x38+) ──────────────────────────────
    // Typed indirection over a managed pointer block (see ManagedPtr).
    // Each LoadPtr.* pops a pointer handle (Obj-tag external) and pushes the
    // dereferenced value read through it, bound-checked against the block.
    Ldptr = 0x38,   // Ldptr.i4   (32-bit int / bool / char)
    LdptrI8 = 0x39, // Ldptr.i8
    LdptrR4 = 0x3A, // Ldptr.r4
    LdptrR8 = 0x3B, // Ldptr.r8
    // Typed store: pops value then pointer handle; writes the value through it.
    StptrI4 = 0x3C,
    StptrI8 = 0x3D,
    StptrR4 = 0x3E,
    StptrR8 = 0x3F,
    PtrAddr = 0x40, // Ptr.addr: pops a pointer handle, pushes raw address as I8
    PtrLen  = 0x41, // Ptr.len:  pops a pointer handle, pushes element count as I4
    PtrAlloc = 0x42,// Ptr.alloc: pops count,size -> creates a PtrBlock, pushes handle
    PtrFree  = 0x43,// Ptr.free:  pops a pointer handle, releases its buffer
}

public static class OpcodeExtensions
{
    public static string ToDisplayString(this Opcode op) => op switch
    {
        Opcode.Nop       => "nop",
        Opcode.Ldc       => "ldc",
        Opcode.Ldstr     => "ldstr",
        Opcode.Ldarg     => "ldarg",
        Opcode.Starg     => "starg",
        Opcode.Ldloc     => "ldloc",
        Opcode.Stloc     => "stloc",
        Opcode.Add       => "add",
        Opcode.Sub       => "sub",
        Opcode.Mul       => "mul",
        Opcode.Div       => "div",
        Opcode.Rem       => "rem",
        Opcode.Neg       => "neg",
        Opcode.Ceq       => "ceq",
        Opcode.Cne       => "cne",
        Opcode.Ldfld     => "ldfld",
        Opcode.Ldsfld    => "ldsfld",
        Opcode.Stsfld    => "stsfld",
        Opcode.Newobj    => "newobj",
        Opcode.Ldlen     => "ldlen",
        Opcode.Newarr    => "newarr",
        Opcode.Ldelem    => "ldelem",
        Opcode.Stelem    => "stelem",
        Opcode.Call      => "call",
        Opcode.Callvirt  => "callvirt",
        Opcode.Ret       => "ret",
        Opcode.If        => "if",
        Opcode.While     => "while",
        Opcode.Break     => "break",
        Opcode.Continue  => "continue",
        Opcode.Try       => "try",
        Opcode.Throw     => "throw",
        Opcode.Conv      => "conv",
        Opcode.Castclass => "castclass",
        Opcode.Isinst    => "isinst",
        Opcode.Dup       => "dup",
        Opcode.Pop       => "pop",
        Opcode.Ldnull    => "ldnull",
        Opcode.Not       => "not",
        Opcode.Cgt       => "cgt",
        Opcode.Cge       => "cge",
        Opcode.Clt       => "clt",
        Opcode.Cle       => "cle",
        Opcode.Stfld     => "stfld",
        Opcode.LdcI4     => "ldc.i4",
        Opcode.LdcI8     => "ldc.i8",
        Opcode.LdcR4     => "ldc.r4",
        Opcode.LdcR8     => "ldc.r8",
        Opcode.And       => "and",
        Opcode.Xor       => "xor",
        Opcode.Or        => "or",
        Opcode.Shl       => "shl",
        Opcode.Br        => "br",
        Opcode.Brtrue    => "brtrue",
        Opcode.Brfalse   => "brfalse",
        Opcode.NativeCall => "callnative",
        Opcode.Ldptr    => "ldptr.i4",
        Opcode.LdptrI8  => "ldptr.i8",
        Opcode.LdptrR4  => "ldptr.r4",
        Opcode.LdptrR8  => "ldptr.r8",
        Opcode.StptrI4  => "stptr.i4",
        Opcode.StptrI8  => "stptr.i8",
        Opcode.StptrR4  => "stptr.r4",
        Opcode.StptrR8  => "stptr.r8",
        Opcode.PtrAddr  => "ptr.addr",
        Opcode.PtrLen   => "ptr.len",
        Opcode.PtrAlloc => "ptr.alloc",
        Opcode.PtrFree  => "ptr.free",
        _                => "???",
    };

    /// <summary>Parse a mnemonic string to an opcode value.</summary>
    public static int FromMnemonic(string mnemonic)
    {
        return mnemonic switch
        {
            "nop"       => 0x00, "ldc"       => 0x01, "ldstr"     => 0x02,
            "ldarg"     => 0x03, "starg"     => 0x04, "ldloc"     => 0x05,
            "stloc"     => 0x06, "add"       => 0x07, "sub"       => 0x08,
            "mul"       => 0x09, "div"       => 0x0A, "rem"       => 0x0B,
            "neg"       => 0x0C, "ceq"       => 0x0D, "cne"       => 0x0E,
            "ldfld"     => 0x0F, "ldsfld"    => 0x10, "stsfld"    => 0x11,
            "newobj"    => 0x12, "newarr"    => 0x13, "ldelem"    => 0x14,
            "stelem"    => 0x15, "call"      => 0x16, "callvirt"  => 0x17,
            "ret"       => 0x18, "if"        => 0x19, "while"     => 0x1A,
            "break"     => 0x1B, "continue"  => 0x1C, "try"       => 0x1D,
            "throw"     => 0x1E, "conv"      => 0x1F, "castclass" => 0x20,
            "isinst"    => 0x21, "dup"       => 0x22, "pop"       => 0x23,
            "ldnull"    => 0x24, "not"       => 0x25, "cgt"       => 0x26,
            "cge"       => 0x27, "clt"       => 0x28, "cle"       => 0x29,
            "stfld"     => 0x2A, "ldc.i4"    => 0x2B, "ldc.i8"    => 0x2C,
            "ldc.r4"    => 0x2D, "ldc.r8"    => 0x2E, "and"       => 0x2F,
            "xor"       => 0x30, "or"        => 0x31, "br"        => 0x32,
            "brtrue"    => 0x33, "brfalse"   => 0x34,             "callnative" => 0x35,
            "ldlen"     => 0x36,
            "shl"       => 0x37,
            "ldptr"     => 0x38, "ldptr.i4"  => 0x38, "ldind.i4" => 0x38,
            "ldptr.i8"  => 0x39, "ldind.i8"  => 0x39,
            "ldptr.r4"  => 0x3A, "ldind.r4"  => 0x3A,
            "ldptr.r8"  => 0x3B, "ldind.r8"  => 0x3B,
            "stptr.i4"  => 0x3C, "stind.i4"  => 0x3C,
            "stptr.i8"  => 0x3D, "stind.i8"  => 0x3D,
            "stptr.r4"  => 0x3E, "stind.r4"  => 0x3E,
            "stptr.r8"  => 0x3F, "stind.r8"  => 0x3F,
            "ptr.addr"  => 0x40,
            "ptr.len"   => 0x41,
            "ptr.alloc" => 0x42,
            "ptr.free"  => 0x43,
            _           => -1,
        };
    }
}
